Hack-#4
finsweet/sweetjs pull request #14
Opened 2022-01-28 03:06 UTC by brayanfinsweet

Create dynamic Webflow CMS generated anchor links.

2022-01-28 10:00 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4.ts
> +  let observer = new IntersectionObserver(
I would use `const` if the variable is never reassigned.
Once we merge my PR that includes ESLint these cases will be warned by the linter.

2022-01-28 10:00 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4.ts
> +    (entries, observer) => {
The `observer` parameter is not used, you can remove it.

2022-01-28 10:00 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4.ts
> +      entries.forEach((entry) => {
You can use destructuring here:
```typescript
entries.forEach(({isIntersecting, target}) => {
```

2022-01-28 10:00 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4.ts
> +            link.classList.remove('hack4-active');
Instead of hardcoding the class name here twice, I would create a constant variable like `const CLASS_NAME="hack4-active"` at the top of the script so it's easier to tweak.

2022-01-28 12:35 UTC, brayanfinsweet commented on webflow-hacks/cms-hacks/4.ts
> +            link.classList.remove('hack4-active');
done

2022-01-28 12:35 UTC, brayanfinsweet commented on webflow-hacks/cms-hacks/4.ts
> +  let observer = new IntersectionObserver(
done

2022-01-28 12:35 UTC, brayanfinsweet commented on webflow-hacks/cms-hacks/4.ts
> +    (entries, observer) => {
done

2022-08-18 11:37 UTC, brayanfinsweet commented
@alexiglesias93 can I merge this?

2022-08-18 14:03 UTC, alexiglesias93 commented
@brayanfinsweet can you implement the early return that I suggested in my previous review?

2022-08-18 14:16 UTC, brayanfinsweet commented
@alexiglesias93 sorry I can't see that review

2022-08-18 14:59 UTC, alexiglesias93 requested changes

2022-08-18 14:59 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4.ts
> +      });
To make this code cleaner, I would do an early return if `!isIntersecting`.
This way there is less indentation, the code stays cleaner,

```typescript
entries.forEach(({ isIntersecting, target }) => {
  // if it's in the viewport
  if (!isIntersecting) return;
  // for each link
  filterLinks.forEach((link) => {
    // remove the active class from the current active link
    link.classList.remove(ACTIVE_CLASS);
    // check if current active link href is the target
    if (link.href === `#${target.id}`) {
      // add the active class to the current active link
      link.classList.add(ACTIVE_CLASS);
    }
  });
});
```

2022-08-18 15:14 UTC, alexiglesias93 requested changes

2022-08-18 15:14 UTC, alexiglesias93 commented on webflow-hacks/cms-hacks/4/4.ts
> +          }
```diff
-          link.classList.remove(ACTIVE_CLASS);
-
-          if (link.href === `#${target.id}`) {
-            link.classList.add(ACTIVE_CLASS);
-          }

+          if (link.href === `#${target.id}`) {
+            link.classList.add(ACTIVE_CLASS);
+          } else {
+            link.classList.remove(ACTIVE_CLASS);
+          }
```

2022-08-18 15:20 UTC, alexiglesias93 approved these changes

2022-08-18 15:21 UTC, merged