Hack-#7
finsweet/sweetjs pull request #15
Opened 2022-01-28 03:40 UTC by brayanfinsweet

Customize Favicon for a specific page.

2022-01-28 10:02 UTC, alexiglesias93 commented on webflow-hacks/misc-hacks/7.ts
> +  document.getElementsByTagName('head')[0].appendChild(link);
There's a simpler approach:
```typescript
  document.head.appendChild(link);
```

2022-02-01 14:24 UTC, alexiglesias93 commented on webflow-hacks/misc-hacks/7.ts
> +  const link = document.querySelector<HTMLAnchorElement>(LINK_SELECTOR) || document.createElement('link');
I think this should not be a custom selector querying a random anchor link on the page.
I believe the orignal script queries the `<link>` element that holds the favicon.

2022-08-18 11:22 UTC, alexiglesias93 requested changes

2022-08-18 11:22 UTC, alexiglesias93 commented on webflow-hacks/misc-hacks/7.ts
> +  const link = document.querySelector<HTMLAnchorElement>(LINK_SELECTOR) || document.createElement('link');
```typescript
const link = document.querySelector<HTMLLinkElement>("link[rel*='icon']") || document.createElement('link');
```

2022-08-18 11:24 UTC, alexiglesias93 requested changes

2022-08-18 11:24 UTC, alexiglesias93 commented on webflow-hacks/misc-hacks/7.ts
> +  const link = document.querySelector<HTMLAnchorElement>(LINK_SELECTOR) || document.createElement('link');
```diff
- const link = document.querySelector<HTMLAnchorElement>(LINK_SELECTOR) || document.createElement('link');
+ const link = document.querySelector<HTMLLinkElement>(LINK_SELECTOR) || document.createElement('link');
```

2022-08-18 11:24 UTC, alexiglesias93 commented
@brayanfinsweet can you check the merging conflicts? Why does this branch remove the `webflow-hacks/form-hacks/1.ts` files?

2022-08-18 11:25 UTC, brayanfinsweet commented
Hi I will add them back. I wanted to remove them to put inside a folder but I used the wrong branch

2022-08-18 14:01 UTC, alexiglesias93 approved these changes

2022-08-18 15:16 UTC, merged