Hack 19: Submit checkboxes, radios, and select as text fields in Mail…
finsweet/sweetjs pull request #33
Opened 2022-06-08 16:03 UTC by brayanfinsweet

…chimp

2022-06-08 16:17 UTC, alexiglesias93 requested changes
Most of this code is unnecessary.
- Select inputs are already sent as text natively.
- Radios are already sent as text natively. It's sent as: `Radio Group Name: Chosen Radio Value`

Only the checkboxes are necessary to be converted from `true | false` to a specific string!

2022-06-08 16:17 UTC, alexiglesias93 commented on webflow-hacks/form-hacks/19/19.ts
> +    e.preventDefault();
You have to call `e.stopPropagation()` if you want to prevent a Webflow form submission

2022-07-27 08:40 UTC, alexiglesias93 commented
@brayanfinsweet I'm having a hard time understanding this new code. Would you mind sharing the website where you're testing it?

2022-07-28 09:16 UTC, brayanfinsweet commented
https://finsweetwebflowhacks-rewrite.webflow.io/19
They say Mailchimp doesn't accept anything other than text/hidden fields on the form action, so the code populates radio and checkbox data to hidden text fields. It seems though that the form action link is no longer working so there is no way to see this in action

2022-07-28 14:47 UTC, alexiglesias93 commented
@brayanfinsweet could you create a free Mailchimp account to test it?

2022-08-18 09:42 UTC, brianndiiri commented
Hi mailchimp has since added these fields to their interface so this solution is outdated
![Screenshot from 2022-08-18 12-40-08](https://user-images.githubusercontent.com/79919228/185364381-a78bd6a3-daf4-419f-a45f-9df826828d1e.png)

2022-08-18 11:18 UTC, alexiglesias93 commented
> Hi mailchimp has since added these fields to their interface so this solution is outdated ![Screenshot from 2022-08-18 12-40-08](https://user-images.githubusercontent.com/79919228/185364381-a78bd6a3-daf4-419f-a45f-9df826828d1e.png)

@brayanfinsweet so this means that no JS is required for submitting checkboxes and radio buttons to Mailchimp, is that correct?
In that case, we can remove this Hack

2022-08-18 11:20 UTC, brayanfinsweet commented
Correct! this pull request will be closed here

2022-08-18 11:20 UTC, closed without merging